#!/usr/bin/env python
"""Minimal training test for ToxiGene molecular encoder.

Loads the synthetic data generated by generate_molecular_data.py and runs
a few training epochs to verify the full pipeline works end-to-end:
  - Data loading (expression, hierarchy, labels)
  - Model construction (MolecularEncoder with sparse hierarchy)
  - Forward pass through bottleneck + hierarchy network
  - Multi-task loss computation (outcome BCE + pathway MSE + L1 sparsity)
  - Backward pass and parameter updates
  - Validation metrics

Usage:
    python scripts/test_molecular_training.py [--data-dir data/processed/molecular]
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import scipy.sparse
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, random_split


class SimpleToxiGeneDataset(Dataset):
    """Lightweight dataset for testing that loads the generated .npz files."""

    def __init__(self, data_dir: str | Path) -> None:
        data_dir = Path(data_dir)

        # Load expression data
        expr_data = np.load(data_dir / "expression_data.npz")
        self.expression = expr_data["expression"].astype(np.float32)

        # Load labels
        label_data = np.load(data_dir / "labels.npz", allow_pickle=True)
        self.labels = label_data["labels"].astype(np.int64)
        self.class_names = list(label_data["class_names"])

        # Load outcome labels
        self.outcome_labels = np.load(data_dir / "outcome_labels.npy").astype(np.float32)

        # Load pathway labels (optional)
        pw_path = data_dir / "pathway_labels.npy"
        self.pathway_labels = (
            np.load(pw_path).astype(np.float32) if pw_path.exists() else None
        )

        print(f"Dataset: {self.expression.shape[0]} samples, {self.expression.shape[1]} genes")
        print(f"  Outcomes: {self.outcome_labels.shape[1]} adverse outcomes")
        if self.pathway_labels is not None:
            print(f"  Pathways: {self.pathway_labels.shape[1]} pathway activations")

    def __len__(self) -> int:
        return self.expression.shape[0]

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        result = {
            "gene_expression": torch.from_numpy(self.expression[idx]),
            "outcome_labels": torch.from_numpy(self.outcome_labels[idx]),
            "class_label": torch.tensor(self.labels[idx], dtype=torch.long),
        }
        if self.pathway_labels is not None:
            result["pathway_labels"] = torch.from_numpy(self.pathway_labels[idx])
        return result


def load_hierarchy(data_dir: Path) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, list[str]]:
    """Load hierarchy adjacency matrices and gene names."""
    # Load sparse adjacency matrices
    npz_files = sorted(data_dir.glob("hierarchy_layer*.npz"))
    if len(npz_files) >= 3:
        pathway_adj = torch.from_numpy(
            scipy.sparse.load_npz(npz_files[0]).toarray()
        ).float()
        process_adj = torch.from_numpy(
            scipy.sparse.load_npz(npz_files[1]).toarray()
        ).float()
        outcome_adj = torch.from_numpy(
            scipy.sparse.load_npz(npz_files[2]).toarray()
        ).float()
    else:
        # Fallback: load from combined hierarchy.npz
        hier_data = np.load(data_dir / "hierarchy.npz")
        pathway_adj = torch.from_numpy(hier_data["pathway_adj"]).float()
        process_adj = torch.from_numpy(hier_data["process_adj"]).float()
        outcome_adj = torch.from_numpy(hier_data["outcome_adj"]).float()

    # Load gene names
    with open(data_dir / "gene_names.json", "r", encoding="utf-8") as f:
        gene_names = json.load(f)

    return pathway_adj, process_adj, outcome_adj, gene_names


def main() -> None:
    parser = argparse.ArgumentParser(description="Test ToxiGene molecular encoder training")
    parser.add_argument("--data-dir", type=str, default="data/processed/molecular")
    parser.add_argument("--epochs", type=int, default=5, help="Training epochs")
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--device", type=str, default="auto")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    print(f"Device: {device}")
    print()

    # -----------------------------------------------------------------------
    # Step 1: Load data
    # -----------------------------------------------------------------------
    print("=" * 60)
    print("Step 1: Loading data")
    print("=" * 60)

    dataset = SimpleToxiGeneDataset(data_dir)
    pathway_adj, process_adj, outcome_adj, gene_names = load_hierarchy(data_dir)

    print(f"Hierarchy shapes:")
    print(f"  pathway_adj: {pathway_adj.shape} (gene -> pathway)")
    print(f"  process_adj: {process_adj.shape} (pathway -> process)")
    print(f"  outcome_adj: {outcome_adj.shape} (process -> outcome)")
    print(f"  Connections: {int(pathway_adj.sum())} gene-pathway, "
          f"{int(process_adj.sum())} pathway-process, {int(outcome_adj.sum())} process-outcome")
    print()

    # Split into train/val
    n_total = len(dataset)
    n_val = max(1, int(n_total * 0.2))
    n_train = n_total - n_val
    train_ds, val_ds = random_split(
        dataset, [n_train, n_val], generator=torch.Generator().manual_seed(42)
    )

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, drop_last=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

    print(f"Train: {n_train} samples, Val: {n_val} samples")
    print()

    # -----------------------------------------------------------------------
    # Step 2: Build model
    # -----------------------------------------------------------------------
    print("=" * 60)
    print("Step 2: Building MolecularEncoder")
    print("=" * 60)

    from sentinel.models.molecular_encoder.model import MolecularEncoder

    model = MolecularEncoder(
        gene_names=gene_names,
        pathway_adj=pathway_adj,
        process_adj=process_adj,
        outcome_adj=outcome_adj,
        num_chem_classes=7,
        lambda_l1=0.01,
        dropout=0.2,
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model parameters: {n_params:,} total, {n_trainable:,} trainable")

    # Print submodule parameter counts
    for name, module in model.named_children():
        n_mod = sum(p.numel() for p in module.parameters())
        print(f"  {name}: {n_mod:,}")
    print()

    # -----------------------------------------------------------------------
    # Step 3: Quick forward pass test
    # -----------------------------------------------------------------------
    print("=" * 60)
    print("Step 3: Forward pass test")
    print("=" * 60)

    batch = next(iter(train_loader))
    gene_expr = batch["gene_expression"].to(device)
    outcome_targets = batch["outcome_labels"].to(device)

    with torch.no_grad():
        outputs = model(gene_expression=gene_expr)

    print(f"Input: gene_expression {gene_expr.shape}")
    for key, val in outputs.items():
        if isinstance(val, torch.Tensor):
            print(f"  {key}: {val.shape} (mean={val.float().mean():.4f})")
        else:
            print(f"  {key}: {val}")
    print()

    # -----------------------------------------------------------------------
    # Step 4: Training loop
    # -----------------------------------------------------------------------
    print("=" * 60)
    print(f"Step 4: Training ({args.epochs} epochs)")
    print("=" * 60)

    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6
    )

    best_val_loss = float("inf")
    train_history = []

    for epoch in range(1, args.epochs + 1):
        # --- Training ---
        model.train()
        epoch_losses = {
            "total": 0.0, "outcome": 0.0, "bottleneck_l1": 0.0, "pathway": 0.0
        }
        n_batches = 0
        t0 = time.time()

        for batch in train_loader:
            gene_expr = batch["gene_expression"].to(device)
            outcome_targets = batch["outcome_labels"].to(device)
            pathway_targets = batch.get("pathway_labels")
            if pathway_targets is not None:
                pathway_targets = pathway_targets.to(device)

            optimizer.zero_grad()

            outputs = model(gene_expression=gene_expr)
            losses = model.compute_loss(
                outputs=outputs,
                outcome_targets=outcome_targets,
                pathway_targets=pathway_targets,
                outcome_weight=1.0,
                pathway_weight=0.5,
                bottleneck_weight=1.0,
            )

            losses["total"].backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            for k in epoch_losses:
                if k in losses:
                    val = losses[k]
                    epoch_losses[k] += val.item() if isinstance(val, torch.Tensor) else float(val)
            n_batches += 1

        scheduler.step()
        train_time = time.time() - t0

        # Average training losses
        for k in epoch_losses:
            epoch_losses[k] /= max(n_batches, 1)

        # --- Validation ---
        model.eval()
        val_total = 0.0
        val_outcome = 0.0
        correct = 0
        total = 0
        n_val_batches = 0

        with torch.no_grad():
            for batch in val_loader:
                gene_expr = batch["gene_expression"].to(device)
                outcome_targets = batch["outcome_labels"].to(device)
                pathway_targets = batch.get("pathway_labels")
                if pathway_targets is not None:
                    pathway_targets = pathway_targets.to(device)

                outputs = model(gene_expression=gene_expr)
                losses = model.compute_loss(
                    outputs=outputs,
                    outcome_targets=outcome_targets,
                    pathway_targets=pathway_targets,
                )

                val_total += losses["total"].item()
                val_outcome += losses["outcome"].item()

                preds = (torch.sigmoid(outputs["outcome_logits"]) > 0.5).float()
                correct += (preds == outcome_targets).sum().item()
                total += outcome_targets.numel()
                n_val_batches += 1

        val_total /= max(n_val_batches, 1)
        val_outcome /= max(n_val_batches, 1)
        val_accuracy = correct / max(total, 1)

        n_selected = model.bottleneck.num_selected

        # Track
        is_best = val_total < best_val_loss
        if is_best:
            best_val_loss = val_total

        train_history.append({
            "epoch": epoch,
            "train_loss": epoch_losses["total"],
            "val_loss": val_total,
            "val_accuracy": val_accuracy,
            "n_selected_genes": n_selected,
        })

        print(
            f"Epoch {epoch:3d}/{args.epochs} | "
            f"Train: {epoch_losses['total']:.4f} "
            f"(out={epoch_losses['outcome']:.4f}, pw={epoch_losses['pathway']:.4f}, "
            f"L1={epoch_losses['bottleneck_l1']:.4f}) | "
            f"Val: {val_total:.4f} (acc={val_accuracy:.4f}) | "
            f"Genes: {n_selected:4d} | "
            f"LR: {scheduler.get_last_lr()[0]:.6f} | "
            f"{train_time:.1f}s"
            + (" *" if is_best else "")
        )

    # -----------------------------------------------------------------------
    # Step 5: Summary
    # -----------------------------------------------------------------------
    print()
    print("=" * 60)
    print("Training Summary")
    print("=" * 60)
    print(f"Best validation loss: {best_val_loss:.4f}")
    print(f"Final validation accuracy: {train_history[-1]['val_accuracy']:.4f}")
    print(f"Selected genes (final): {train_history[-1]['n_selected_genes']}")
    print()

    # Show selected genes (top 20 by gate value)
    gate_values = model.bottleneck.gates.detach().cpu()
    top_indices = torch.argsort(gate_values, descending=True)[:20]
    print("Top 20 genes by gate value:")
    for rank, idx in enumerate(top_indices):
        print(f"  {rank+1:3d}. {gene_names[idx]:20s} gate={gate_values[idx]:.4f}")

    # Test interpretable activations
    print()
    print("Interpretable activation test:")
    test_batch = next(iter(val_loader))
    gene_expr = test_batch["gene_expression"][:4].to(device)
    with torch.no_grad():
        interp = model.get_interpretable_activations(gene_expr)
    for k, v in interp.items():
        if isinstance(v, torch.Tensor):
            print(f"  {k}: {v.shape}")
        elif isinstance(v, list):
            print(f"  {k}: {len(v)} items")

    # Test chemistry-only mode
    print()
    print("Chemistry-only mode test:")
    chem_class = F.one_hot(torch.tensor([0, 1, 2, 3]), num_classes=7).float().to(device)
    log_conc = torch.tensor([-3.0, -2.0, -1.0, 0.0]).to(device)
    with torch.no_grad():
        chem_outputs = model(chem_class=chem_class, log_concentration=log_conc)
    for k, v in chem_outputs.items():
        if isinstance(v, torch.Tensor):
            print(f"  {k}: {v.shape}")

    print()
    print("SUCCESS: ToxiGene molecular encoder training pipeline verified!")
    print(f"  Model can train on {n_train} samples with {len(gene_names)} genes")
    print(f"  Hierarchy: {pathway_adj.shape[1]} genes -> {pathway_adj.shape[0]} pathways "
          f"-> {process_adj.shape[0]} processes -> {outcome_adj.shape[0]} outcomes")


if __name__ == "__main__":
    main()
