#!/usr/bin/env python3
"""
BioMotion retrain on expanded ECOTOX Daphnia behavioral dataset.

Loads from data/processed/behavioral_fullreal/ (generated by expand_biomotion_data.py).
Same architecture as phase2_best.pt:
  - TrajectoryDiffusionEncoder (Phase 1 diffusion pretraining on normal trajectories)
  - AnomalyClassifier head (Phase 2 supervised fine-tuning)

50 epochs per phase, early stopping patience=10 for Phase 2.
Saves best model to checkpoints/biomotion/biomotion_expanded_best.pt.
Saves results to checkpoints/biomotion/results_expanded.json.

Usage:
    CUDA_VISIBLE_DEVICES=3 python scripts/train_biomotion_expanded.py
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from sentinel.models.biomotion.trajectory_encoder import TrajectoryDiffusionEncoder, EMBED_DIM
from sentinel.models.biomotion.multi_organism import SPECIES_FEATURE_DIM

# ── Config ─────────────────────────────────────────────────────────────────
DATA_DIR  = PROJECT_ROOT / "data" / "processed" / "behavioral_fullreal"
CKPT_DIR  = PROJECT_ROOT / "checkpoints" / "biomotion"
CKPT_DIR.mkdir(parents=True, exist_ok=True)

FEATURE_DIM  = SPECIES_FEATURE_DIM["daphnia"]   # 16
N_KEYPOINTS  = 12
BATCH_SIZE   = 64
SEED         = 42
TEST_FRAC    = 0.15
VAL_FRAC     = 0.15

# Phase 1: diffusion pretraining on normal trajectories
P1_EPOCHS   = 50
P1_LR       = 2e-4
P1_WARMUP   = 400

# Phase 2: supervised classification fine-tuning
P2_EPOCHS   = 50
P2_LR       = 5e-5
P2_WARMUP   = 200
EARLY_STOP_PATIENCE = 10


# ── Dataset ────────────────────────────────────────────────────────────────

class BehavioralDataset(Dataset):
    def __init__(self, file_paths: list[Path]) -> None:
        self.fps = file_paths
        self._cache: dict[int, dict] = {}

    def __len__(self) -> int:
        return len(self.fps)

    def __getitem__(self, idx: int) -> dict:
        if idx not in self._cache:
            d = np.load(self.fps[idx])
            self._cache[idx] = {
                "keypoints":  d["keypoints"].astype(np.float32),
                "features":   d["features"].astype(np.float32),
                "timestamps": d["timestamps"].astype(np.float32),
                "is_anomaly": bool(d["is_anomaly"]),
            }
        return self._cache[idx]

    @staticmethod
    def collate(batch: list[dict]) -> dict[str, torch.Tensor]:
        return {
            "keypoints":  torch.from_numpy(np.stack([s["keypoints"]  for s in batch])),
            "features":   torch.from_numpy(np.stack([s["features"]   for s in batch])),
            "timestamps": torch.from_numpy(np.stack([s["timestamps"] for s in batch])),
            "labels":     torch.tensor([float(s["is_anomaly"]) for s in batch], dtype=torch.float32),
        }


# ── Data loading ───────────────────────────────────────────────────────────

def load_data() -> tuple[BehavioralDataset, BehavioralDataset, BehavioralDataset, BehavioralDataset]:
    all_files = sorted(DATA_DIR.glob("traj_*.npz"))
    assert len(all_files) > 0, f"No trajectory files found in {DATA_DIR}"
    print(f"Found {len(all_files)} trajectories in {DATA_DIR}")

    normal_files, anomaly_files = [], []
    for f in all_files:
        d = np.load(f)
        (anomaly_files if bool(d["is_anomaly"]) else normal_files).append(f)

    print(f"  Normal: {len(normal_files)},  Anomalous: {len(anomaly_files)}")

    rng = np.random.default_rng(SEED)
    rng.shuffle(normal_files)
    rng.shuffle(anomaly_files)

    def split(lst):
        n = len(lst)
        n_te = max(1, int(n * TEST_FRAC))
        n_va = max(1, int(n * VAL_FRAC))
        return lst[:n - n_te - n_va], lst[n - n_te - n_va : n - n_te], lst[n - n_te:]

    n_tr, n_va, n_te = split(normal_files)
    a_tr, a_va, a_te = split(anomaly_files)

    print(f"  Train: {len(n_tr)+len(a_tr)}  Val: {len(n_va)+len(a_va)}  Test: {len(n_te)+len(a_te)}")

    return (
        BehavioralDataset(n_tr),                     # phase-1 normal only
        BehavioralDataset(n_tr + a_tr),              # phase-2 all train
        BehavioralDataset(n_va + a_va),              # val
        BehavioralDataset(n_te + a_te),              # test
    )


def make_loader(ds: BehavioralDataset, shuffle: bool, bs: int = BATCH_SIZE) -> DataLoader:
    return DataLoader(ds, batch_size=bs, shuffle=shuffle,
                      collate_fn=BehavioralDataset.collate,
                      num_workers=4, pin_memory=True,
                      drop_last=(shuffle))


# ── LR schedule ───────────────────────────────────────────────────────────

def cosine_schedule(optimizer, total_steps: int, warmup: int):
    def lr_lambda(step: int) -> float:
        if step < warmup:
            return step / max(1, warmup)
        p = (step - warmup) / max(1, total_steps - warmup)
        return 0.01 + 0.5 * 0.99 * (1 + math.cos(math.pi * p))
    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


# ── Model ──────────────────────────────────────────────────────────────────

class AnomalyClassifier(nn.Module):
    def __init__(self, encoder: TrajectoryDiffusionEncoder) -> None:
        super().__init__()
        self.encoder = encoder
        self.classifier = nn.Sequential(
            nn.Linear(EMBED_DIM, EMBED_DIM // 2),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(EMBED_DIM // 2, 1),
        )
        for m in self.classifier.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        emb = self.encoder.forward_encode(features)
        return self.classifier(emb).squeeze(-1)


# ── Phase 1 ────────────────────────────────────────────────────────────────

def train_phase1(encoder, train_ds, val_ds, device) -> dict:
    print("\n" + "=" * 70)
    print("PHASE 1: Diffusion Pretraining (normal trajectories, 50 epochs)")
    print("=" * 70)
    encoder.to(device)
    tr_ld = make_loader(train_ds, shuffle=True)
    va_ld = make_loader(val_ds,   shuffle=False, bs=BATCH_SIZE)

    opt = torch.optim.AdamW(encoder.parameters(), lr=P1_LR, weight_decay=0.01)
    sch = cosine_schedule(opt, len(tr_ld) * P1_EPOCHS, P1_WARMUP)

    best_val = float("inf")
    hist = {"train_loss": [], "val_loss": []}
    t0 = time.time()

    for epoch in range(P1_EPOCHS):
        encoder.train()
        ep_loss = []
        for batch in tr_ld:
            feats = batch["features"].to(device)
            loss  = encoder.compute_training_loss(feats)["loss"]
            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(encoder.parameters(), 1.0)
            opt.step(); sch.step()
            ep_loss.append(loss.item())
        tr_loss = float(np.mean(ep_loss))

        encoder.eval()
        va_loss = []
        with torch.no_grad():
            for batch in va_ld:
                feats = batch["features"].to(device)
                va_loss.append(encoder.compute_training_loss(feats)["loss"].item())
        val_loss = float(np.mean(va_loss)) if va_loss else float("inf")

        hist["train_loss"].append(tr_loss)
        hist["val_loss"].append(val_loss)

        if val_loss < best_val:
            best_val = val_loss
            torch.save({"epoch": epoch, "model_state_dict": encoder.state_dict(),
                        "val_loss": val_loss}, CKPT_DIR / "expanded_phase1_best.pt")

        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"  Epoch {epoch+1:3d}/{P1_EPOCHS}  tr={tr_loss:.6f}  "
                  f"va={val_loss:.6f}  lr={opt.param_groups[0]['lr']:.2e}  "
                  f"time={time.time()-t0:.0f}s")

    print(f"Phase 1 done in {time.time()-t0:.0f}s | best_val_loss={best_val:.6f}")
    state = torch.load(CKPT_DIR / "expanded_phase1_best.pt", map_location=device, weights_only=False)
    encoder.load_state_dict(state["model_state_dict"])
    return {"best_val_loss": best_val, "history": hist}


# ── Phase 2 ────────────────────────────────────────────────────────────────

def train_phase2(encoder, train_ds, val_ds, device) -> tuple[AnomalyClassifier, dict]:
    print("\n" + "=" * 70)
    print("PHASE 2: Anomaly Classification (50 epochs, patience=10)")
    print("=" * 70)
    model = AnomalyClassifier(encoder)
    model.to(device)
    tr_ld = make_loader(train_ds, shuffle=True)
    va_ld = make_loader(val_ds,   shuffle=False, bs=BATCH_SIZE)

    param_groups = [
        {"params": model.encoder.parameters(),    "lr": P2_LR},
        {"params": model.classifier.parameters(), "lr": P2_LR * 5},
    ]
    opt = torch.optim.AdamW(param_groups, weight_decay=0.01)
    sch = cosine_schedule(opt, len(tr_ld) * P2_EPOCHS, P2_WARMUP)

    best_val = float("inf")
    best_acc = 0.0
    no_improve = 0
    hist = {"train_loss": [], "val_loss": [], "val_acc": []}
    t0 = time.time()
    best_epoch = 0

    for epoch in range(P2_EPOCHS):
        model.train()
        ep_loss = []
        for batch in tr_ld:
            feats  = batch["features"].to(device)
            labels = batch["labels"].to(device)
            logits = model(feats)
            loss   = F.binary_cross_entropy_with_logits(logits, labels)
            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step(); sch.step()
            ep_loss.append(loss.item())
        tr_loss = float(np.mean(ep_loss))

        model.eval()
        va_losses, correct, total = [], 0, 0
        with torch.no_grad():
            for batch in va_ld:
                feats  = batch["features"].to(device)
                labels = batch["labels"].to(device)
                logits = model(feats)
                va_losses.append(F.binary_cross_entropy_with_logits(logits, labels).item())
                preds   = (torch.sigmoid(logits) > 0.5).float()
                correct += (preds == labels).sum().item()
                total   += len(labels)
        val_loss = float(np.mean(va_losses)) if va_losses else float("inf")
        val_acc  = correct / max(total, 1)

        hist["train_loss"].append(tr_loss)
        hist["val_loss"].append(val_loss)
        hist["val_acc"].append(val_acc)

        if val_loss < best_val:
            best_val = val_loss; best_acc = val_acc; no_improve = 0; best_epoch = epoch
            torch.save({"epoch": epoch, "model_state_dict": model.state_dict(),
                        "val_loss": val_loss, "val_acc": val_acc},
                       CKPT_DIR / "biomotion_expanded_best.pt")
        else:
            no_improve += 1

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"  Epoch {epoch+1:3d}/{P2_EPOCHS}  tr={tr_loss:.4f}  "
                  f"va={val_loss:.4f}  acc={val_acc:.4f}  "
                  f"lr={opt.param_groups[0]['lr']:.2e}  "
                  f"patience={no_improve}/{EARLY_STOP_PATIENCE}")

        if no_improve >= EARLY_STOP_PATIENCE:
            print(f"\nEarly stopping at epoch {epoch+1} (best epoch {best_epoch+1})")
            break

    print(f"Phase 2 done in {time.time()-t0:.0f}s | best_val={best_val:.4f} acc={best_acc:.4f}")
    state = torch.load(CKPT_DIR / "biomotion_expanded_best.pt", map_location=device, weights_only=False)
    model.load_state_dict(state["model_state_dict"])
    return model, {"best_val_loss": best_val, "best_val_acc": best_acc,
                   "best_epoch": best_epoch, "history": hist}


# ── Evaluation ─────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate(model, test_ds, device) -> dict:
    from sklearn.metrics import roc_auc_score, f1_score, precision_score, recall_score, accuracy_score

    print("\n" + "=" * 70)
    print("TEST SET EVALUATION")
    print("=" * 70)
    model.to(device); model.eval()
    ld = make_loader(test_ds, shuffle=False, bs=BATCH_SIZE)

    y_true, y_scores, y_pred = [], [], []
    for batch in ld:
        feats  = batch["features"].to(device)
        labels = batch["labels"]
        probs  = torch.sigmoid(model(feats)).cpu().numpy()
        y_true.append(labels.numpy())
        y_scores.append(probs)
        y_pred.append((probs > 0.5).astype(float))

    y_true   = np.concatenate(y_true)
    y_scores = np.concatenate(y_scores)
    y_pred   = np.concatenate(y_pred)

    auroc     = float(roc_auc_score(y_true, y_scores))
    f1        = float(f1_score(y_true, y_pred))
    precision = float(precision_score(y_true, y_pred))
    recall    = float(recall_score(y_true, y_pred))
    accuracy  = float(accuracy_score(y_true, y_pred))

    print(f"\n  Samples:   {len(y_true)}")
    print(f"  Normal:    {int((y_true == 0).sum())}")
    print(f"  Anomalous: {int((y_true == 1).sum())}")
    print(f"\n  AUROC:     {auroc:.4f}")
    print(f"  F1:        {f1:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  Accuracy:  {accuracy:.4f}")

    # Also compute diffusion-based score
    diff_scores = []
    for batch in ld:
        feats = batch["features"].to(device)
        ds_   = model.encoder.compute_anomaly_score(feats, num_noise_levels=5)
        diff_scores.append(ds_.cpu().numpy())
    diff_scores = np.concatenate(diff_scores)
    diff_auroc  = float(roc_auc_score(y_true, diff_scores))
    print(f"  Diffusion AUROC: {diff_auroc:.4f}")

    return {
        "n_test": int(len(y_true)),
        "n_normal": int((y_true == 0).sum()),
        "n_anomalous": int((y_true == 1).sum()),
        "auroc": auroc,
        "f1": f1,
        "precision": precision,
        "recall": recall,
        "accuracy": accuracy,
        "diffusion_auroc": diff_auroc,
    }


# ── Main ───────────────────────────────────────────────────────────────────

def main() -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    if device.type == "cuda":
        print(f"  GPU: {torch.cuda.get_device_name()}")
        print(f"  VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    torch.manual_seed(SEED); np.random.seed(SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(SEED)

    train_normal, train_all, val_ds, test_ds = load_data()

    encoder = TrajectoryDiffusionEncoder(
        feature_dim=FEATURE_DIM, embed_dim=EMBED_DIM,
        nhead=4, num_layers=4, dim_feedforward=512, dropout=0.1,
    )
    n_params = sum(p.numel() for p in encoder.parameters())
    print(f"\nEncoder parameters: {n_params:,}")

    p1_res = train_phase1(encoder, train_normal, val_ds, device)
    model, p2_res = train_phase2(encoder, train_all, val_ds, device)
    test_res = evaluate(model, test_ds, device)

    results = {
        "model": "BioMotion (TrajectoryDiffusionEncoder + AnomalyClassifier)",
        "species": "daphnia",
        "feature_dim": FEATURE_DIM,
        "embed_dim": EMBED_DIM,
        "n_parameters": n_params,
        "data_sources": [
            "data/processed/behavioral_real/ (17074 original files)",
            "data/raw/ecotox/ (expanded ECOTOX: BEH+MOR+PHY+MVT+REP+ITX+ENZ+DVP+GRO+AVO+IMM+NER+FDB)",
        ],
        "n_train": len(train_all),
        "n_val":   len(val_ds),
        "n_test":  len(test_ds),
        "phase1":  p1_res,
        "phase2":  p2_res,
        "test_auroc": test_res["auroc"],
        "test_f1":    test_res["f1"],
        "test":    test_res,
        "checkpoint": str(CKPT_DIR / "biomotion_expanded_best.pt"),
    }

    out_path = CKPT_DIR / "results_expanded.json"
    with open(out_path, "w") as fh:
        json.dump(results, fh, indent=2, default=str)

    print(f"\n{'='*70}")
    print(f"Results → {out_path}")
    print(f"{'='*70}")
    print(f"  AUROC:           {test_res['auroc']:.4f}")
    print(f"  F1:              {test_res['f1']:.4f}")
    print(f"  Accuracy:        {test_res['accuracy']:.4f}")
    print(f"  Diffusion AUROC: {test_res['diffusion_auroc']:.4f}")
    print(f"  n_train:         {len(train_all)}")
    print(f"  n_val:           {len(val_ds)}")
    print(f"  n_test:          {len(test_ds)}")


if __name__ == "__main__":
    main()
